[package]
name = "zlaunch"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "7c724c0f1049e610c541c2f4f6a8739f91865e02" }
gpui-component = "0.4.1"
gpui-component-assets = "0.4.1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
freedesktop-desktop-entry = "0.7"
freedesktop-icons = "0.4"
dirs = "5"
flume = "0.11"
fuzzy-matcher = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lazy_static = "1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fasteval = "0.2"
arboard = { version = "3", features = ["wayland-data-control"] }
regex = "1"

[patch.crates-io]
gpui = { git = "https://github.com/zed-industries/zed", rev = "7c724c0f1049e610c541c2f4f6a8739f91865e02" }
